# program.md — the autohomelab research agenda

Durable, human-maintained agenda for the autonomous tuning agent, mirrored on
[karpathy/autoresearch](https://github.com/karpathy/autoresearch) and on the prior
`homelab-tooling` loop. The agent reads this file and the current runbook, proposes one change,
benchmarks it, and keeps or discards by the metric. Substitution from autoresearch: **maximize
tok/s** instead of minimize `val_bpb`.

## Setup

- Target one `(node, model)` pair. Node = fingerprint from `scripts/probe.sh`
  (`results/<node_fp>/node_profile.json`); model = HF id + pinned revision.
- Agree a **run tag** (e.g. `20260613`) and work on a branch `autoresearch/<tag>` off `main`.
- **First run is always the baseline**: `runbooks/<org>/<model>/baseline.sh` as-is (generated by
  `scripts/gen_baseline.py`).
- Confirm **N** (benchmark repeats per config); default **N=3**, take the **median** tok/s. Do
  not change N mid-run — it moves the variance floor and invalidates cross-iteration comparison.
  (Lesson from `homelab-tooling`: single-sample scoring chases noise, not signal.)

## What you may change

The **entire runbook `.sh`** for the current `(node, model)` — it is the complete reproducible
unit: pinned image + model + serving flags. Everything else is locked (probe, bench harness,
model weights).

Tunable dimensions:
- **Serving flags**: `max-num-seqs`, `max-num-batched-tokens`, `gpu-memory-utilization`,
  `kv-cache-dtype`, chunked prefill, prefix caching, `async-scheduling`, `max-model-len`,
  attention/moe backend, cudagraph capture sizes, speculative config.
- **The image version itself** (`VLLM_IMAGE`): a real dimension — a newer pinned image can change
  available kernels/backends. Pin any new image by digest in `backends/vllm/image.lock` first.

**All else equal, simpler is better.** A change must earn its complexity with a real tok/s gain.
The model, request distribution, and the GuideLLM sweep are the controlled variables.

## Knowing the option space (don't rely on memory)

vLLM moves fast — enumerate features from the image, never from recall:
- `scripts/capabilities.sh [image]` snapshots `vllm serve --help=all` + the choice-lists for
  `--linear-backend`/`--moe-backend`/`--attention-backend`/`--kv-cache-dtype`/… + `vllm.envs`
  names → `backends/vllm/capabilities/<ver>.txt`. Candidate backends come from THESE lists.
- New features need a newer image (a tuning dimension): pin a newer digest in the registry,
  re-run `capabilities.sh`, and **diff** the snapshots — new flags/choices become experiments.
- Watch `source/vllm` (gitignored clone) commits/releases for sm_121/NVFP4 work; vet non-obvious
  additions with a research agent before adopting.

## Objective & metric

Maximize **median c16 tok/s** (the bulk operating point that responds to the throughput knobs).
**c1 is a sentinel only** — it catches crashes/GEMM-path regressions and gives the latency number,
but is insensitive to batching knobs, so never optimize on it. Routine matrix `LEVELS_SET=1,16`;
run the full `1,4,8,16,32` periodically to confirm c16 stays representative.

## The experiment loop

1. `uv run scripts/tune_status.py --model <m>` → see the current best (★) and leaderboard.
2. Decide **one** change (image or a serving flag). `scripts/new_variant.sh <best.sh> <slug>` →
   a dated `<YYYYMMDD>_<slug>_tuned.sh`; edit its ONE delta and fill the header
   (Deltas / Hypothesis). One change per variant so the result is attributable.
3. `git commit` the variant (one change per commit).
4. `N=3 scripts/run_experiment.sh <that .sh>` — serves once, benches N times (amortized load),
   tears down, prints `MEDIAN c16=… c1=… status=ok|crash`. The watchdog turns a hang into a fast
   `crash` row + auto-teardown. (On unified nodes, `drop_caches` first if sudo is available.)
5. Add a narrative line to `logbook.md`: the delta, median c16 vs best, and the call.
6. **Keep** if median c16 beats the current best beyond noise (rule of thumb: >~3%, and c1 didn't
   regress / didn't crash) → that variant is the new base for the next change. Else **discard**
   (leave it in the tree as a recorded negative). Either way **continue — do not pause to ask.**

## Finalizing a campaign

When a model's tuning is done, promote the winner: `scripts/promote.sh <best_tuned.sh> "<result>"`
→ `<...>_final.sh` (the canonical config to serve). Keep all `*_tuned.sh` artifacts. Record the
final curve in `logbook.md`.

## Output & logging

`run_experiment.sh` writes N `results.tsv` rows tagged `notes: exp=<id>` (raw status `measured`,
or `crash` on a hang), each with per-level JSON bundles under `data/<run_id>/`. The **leaderboard
(`tune_status.py`) decides best by median c16** — keep/discard is a narrative call recorded in
`logbook.md`, not a per-row status. Schema in AGENTS.md.

## Reproducibility (non-negotiable)

- Image pinned by `sha256:` digest in the runbook; tooling pinned via `uv.lock`.
- `logbook.md` opens each session with the environment block (driver, firmware, CUDA, image
  digest, vLLM version, GuideLLM version, model revision) — see docs/reproducibility.md.
- Before pulling/running any image, inventory local docker images/containers first.
