#!/usr/bin/bash
#
# Serve gemma-4-31b-it-nvfp4 with vLLM on NVIDIA GB10 (Grace-Blackwell, sm_121).
# Canonical, fully-validated serve config (passed all three gates: works / good / fast).
# AUTO-GENERATED by scripts/gen_launcher.sh from runbooks/RedHatAI/gemma-4-31B-it-NVFP4/VLLM-23-RedHatAI_gemma-4-31B-it_NVFP4_final.sh — do not hand-edit.
#
# Serves the OpenAI-compatible API on http://0.0.0.0:${PORT:-8000}/v1. Weights load from the host
# HF cache ($HF_HOME or ~/.cache/huggingface); set HF_TOKEN to pull on first run. Runs DETACHED:
#   docker logs -f <NAME>   # follow startup/serving logs    (NAME defaults below)
#   docker rm -f  <NAME>    # stop + remove the container
#   PORT=8001 NAME=foo ./VLLM-23-RedHatAI_gemma-4-31B-it_NVFP4.sh   # override the published port / container name
#

# Upstream vLLM v0.23.0 pinned by digest for reproducibility — the release tag is already immutable;
# the digest makes it byte-exact. Blackwell kernels are built sm_120 (forward-compatible to the
# GB10's sm_121); FlashInfer JITs the FP4/MoE paths for the device at runtime.
export VLLM_IMAGE="vllm/vllm-openai@sha256:6d8429e38e3747723ca07ee1b17972e09bb9c51c4032b266f24fb1cc3b22ed8f"  # v0.23.0
export MODEL="RedHatAI/gemma-4-31B-it-NVFP4"
export MODEL_REVISION="c4905986988f1406d7d7d80200d81099977a9123"   # pinned for reproducibility

# Validated serving context (the benchmark shape). Lower it to raise the guaranteed concurrency
# floor; raise toward the model's native context for long-context serving (KV pool = util below).
export MAX_MODEL_LEN=8192

NAME="${NAME:-vllm-gemma-4-31b-it-nvfp4}"
PORT="${PORT:-8000}"
HF_CACHE="${HF_HOME:-$HOME/.cache/huggingface}"

# Replace any prior container of this name.
docker rm -f "${NAME}" 2>/dev/null || true

docker run -d --name "${NAME}" \
	--gpus all \
	--ipc=host \
	-p "${PORT}:8000" \
	-v "${HF_CACHE}:/root/.cache/huggingface" \
	-e TOKENIZERS_PARALLELISM=false \
	-e "HF_TOKEN=${HF_TOKEN:-}" \
	"${VLLM_IMAGE}" \
		"${MODEL}" \
		--served-model-name gemma-4-31b-it-nvfp4 \
		--revision "${MODEL_REVISION}" \
		--max-model-len "${MAX_MODEL_LEN}" \
		--tensor-parallel-size 1 \
		--gpu-memory-utilization 0.5 \
		--override-generation-config '{"temperature":1.0,"top_p":0.95,"top_k":64}' \
		--enable-auto-tool-choice \
		--tool-call-parser gemma4 \
		--reasoning-parser gemma4 \
		--limit-mm-per-prompt '{"image":0}'
