#!/usr/bin/env bash
# AUTO-GENERATED by scripts/gen_launcher.sh from runbooks/.../VLLM-23-WeiboAI_VibeThinker-3B_final.sh.
# Canonical, fully-validated vLLM serve config (passed all three gates). Self-contained:
# pinned image digest + model + revision + flags inlined. Serves on http://HOST:PORT/v1.
#   ./VLLM-23-WeiboAI_VibeThinker-3B.sh            # serve in the foreground (Ctrl-C stops + removes the container)
#   PORT=8001 NAME=foo ./VLLM-23-WeiboAI_VibeThinker-3B.sh   # override the port / container name
#   (needs: docker + NVIDIA runtime; the model weights pulled to the HF cache, or HF_TOKEN set to fetch.)
set -euo pipefail

VLLM_IMAGE=vllm/vllm-openai@sha256:6d8429e38e3747723ca07ee1b17972e09bb9c51c4032b266f24fb1cc3b22ed8f
MODEL=WeiboAI/VibeThinker-3B
MODEL_REVISION=0c7115fdd0957b3da0f2a0829ab1763969d30300
SERVED_NAME=vibethinker-3b
PORT="${PORT:-8000}"
NAME="${NAME:-vllm-vibethinker-3b}"
HF_CACHE="${HF_HOME:-$HOME/.cache/huggingface}"

# env passed into the container (HF_TOKEN for gated/uncached pulls, plus any runbook VLLM_ENV)
ENV_ARGS=( -e "HF_TOKEN=${HF_TOKEN:-}" )

# validated serving flags (one token per line; exact, including JSON values)
VLLM_FLAGS=(
  --tensor-parallel-size
  1
  --gpu-memory-utilization
  0.5
  --max-model-len
  40960
  --override-generation-config
  \{\"temperature\":1.0\,\"top_p\":0.95\,\"top_k\":-1\}
)

REV_ARGS=(); [ -n "$MODEL_REVISION" ] && REV_ARGS=( --revision "$MODEL_REVISION" )
docker rm -f "$NAME" >/dev/null 2>&1 || true
echo "serving $SERVED_NAME ($MODEL${MODEL_REVISION:+ @$MODEL_REVISION}) on http://0.0.0.0:${PORT}/v1 — Ctrl-C to stop" >&2

exec docker run --rm --name "$NAME" --ipc=host --gpus all \
  -p "${PORT}:8000" "${ENV_ARGS[@]}" \
  -v "${HF_CACHE}:/root/.cache/huggingface" \
  "$VLLM_IMAGE" "$MODEL" \
    --served-model-name "$SERVED_NAME" "${REV_ARGS[@]}" "${VLLM_FLAGS[@]}"
