#!/usr/bin/env bash
# gen_launcher.sh <final_runbook.sh> [<final_runbook.sh> ...] — emit a self-contained, executable
# docker launch script under launchers/ for each promoted `_final.sh`. The launcher inlines the
# pinned image digest + model + revision + validated serving flags (no dependency on the repo,
# adapter.sh, or image.lock) so it can be copied to any GB10-class host and run to serve the model.
#
# The emitted script follows the hand-written ~/bin/docker-vllm-*.sh house style:
#   - `export VLLM_IMAGE / MODEL / MAX_MODEL_LEN` up top (image pinned by digest, with a version note)
#   - flags inlined into a tab-indented `docker run`, not a VLLM_FLAGS=() array
#   - DETACHED (`docker run -d`) like the bin scripts: `docker logs -f <NAME>` to follow, `docker rm -f <NAME>` to stop
#   - `-e TOKENIZERS_PARALLELISM=false`; HF cache mounted; HF_TOKEN passed through for gated/uncached pulls
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
IMAGE_LOCK="$REPO_ROOT/backends/vllm/image.lock"
# shellcheck disable=SC1091
source "$IMAGE_LOCK"
OUTDIR="$REPO_ROOT/launchers"; mkdir -p "$OUTDIR"

# Shell-quote a token for readable inline use: bare when it's a plain flag/value, single-quoted
# (with embedded ' escaped) when it carries JSON or other shell metacharacters.
shq() {
  local s="$1"
  case "$s" in
    ''|*[!A-Za-z0-9_.,:/=@%+-]*)
      s="${s//\'/\'\\\'\'}"            # ' -> '\''
      printf "'%s'" "$s" ;;
    *) printf '%s' "$s" ;;
  esac
}

gen_one() {
  local rb="$1"
  [ -f "$rb" ] || { echo "not found: $rb" >&2; return 1; }
  # Source the runbook in a clean set of vars (reset each call).
  local MODEL="" SERVED_NAME="" MODEL_REVISION="" VLLM_IMAGE="$AHL_VLLM_DEFAULT_IMAGE"
  local VLLM_ENTRYPOINT_SERVE="$AHL_VLLM_DEFAULT_ENTRYPOINT_SERVE"
  local VLLM_FLAGS=() VLLM_ENV=()
  # shellcheck disable=SC1090
  source "$rb"
  : "${MODEL:?$rb must set MODEL}"; : "${SERVED_NAME:=$MODEL}"

  # Resolve the image's vLLM version from the image.lock catalog (for the header note).
  # Optional `v` prefix: stock lines read `v0.23.0`, patched-image lines read `0.23.0-<suffix>`.
  # `|| true` so an unmatched grep can't trip set -e/pipefail (the fallback below handles empty).
  local ver; ver="$(grep -F "$VLLM_IMAGE" "$IMAGE_LOCK" | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)"
  [ -n "$ver" ] || ver="(see backends/vllm/image.lock)"

  # Pull --max-model-len out into its own exported MAX_MODEL_LEN var (bin-script convention);
  # keep every other flag for the inline block.
  local MAX_MODEL_LEN="" skip=0 tok
  local FILTERED=()
  for tok in "${VLLM_FLAGS[@]}"; do
    if [ "$skip" = 1 ]; then MAX_MODEL_LEN="$tok"; skip=0; continue; fi
    if [ "$tok" = "--max-model-len" ]; then skip=1; continue; fi
    FILTERED+=( "$tok" )
  done

  # Group the remaining flags into one line per `--flag [values...]`, quoting each token.
  local FLAG_LINES=() cur=""
  for tok in "${FILTERED[@]}"; do
    if [[ "$tok" == --* ]]; then
      [ -n "$cur" ] && FLAG_LINES+=( "$cur" )
      cur="$(shq "$tok")"
    else
      cur="$cur $(shq "$tok")"
    fi
  done
  [ -n "$cur" ] && FLAG_LINES+=( "$cur" )

  local base; base="$(basename "$rb" .sh)"; base="${base%_final}"
  local out="$OUTDIR/${base}.sh"
  local nodef="vllm-${SERVED_NAME}"

  # Assemble the indented serve arguments (model + serve flags, double-tab block).
  local serve_args=()
  if [ "$VLLM_ENTRYPOINT_SERVE" = "true" ]; then
    serve_args+=( '"${MODEL}"' )                 # image ENTRYPOINT is already `vllm serve`
  else
    serve_args+=( 'vllm serve "${MODEL}"' )
  fi
  serve_args+=( "--served-model-name $(shq "$SERVED_NAME")" )
  [ -n "$MODEL_REVISION" ] && serve_args+=( '--revision "${MODEL_REVISION}"' )
  [ -n "$MAX_MODEL_LEN" ]  && serve_args+=( '--max-model-len "${MAX_MODEL_LEN}"' )
  serve_args+=( "${FLAG_LINES[@]}" )

  {
    echo '#!/usr/bin/bash'
    echo '#'
    echo "# Serve ${SERVED_NAME} with vLLM on NVIDIA GB10 (Grace-Blackwell, sm_121)."
    echo '# Canonical, fully-validated serve config (passed all three gates: works / good / fast).'
    echo "# AUTO-GENERATED by scripts/gen_launcher.sh from $(realpath --relative-to="$REPO_ROOT" "$rb") — do not hand-edit."
    echo '#'
    echo '# Serves the OpenAI-compatible API on http://0.0.0.0:${PORT:-8000}/v1. Weights load from the host'
    echo '# HF cache ($HF_HOME or ~/.cache/huggingface); set HF_TOKEN to pull on first run. Runs DETACHED:'
    echo '#   docker logs -f <NAME>   # follow startup/serving logs    (NAME defaults below)'
    echo '#   docker rm -f  <NAME>    # stop + remove the container'
    echo '#   PORT=8001 NAME=foo ./'"$(basename "$out")"'   # override the published port / container name'
    echo '#'
    echo
    if [[ "$VLLM_IMAGE" == *"@sha256:"* ]]; then
      # Portable upstream image, pinned by content digest.
      echo "# Upstream vLLM ${ver} pinned by digest for reproducibility — the release tag is already immutable;"
      echo '# the digest makes it byte-exact. Blackwell kernels are built sm_120 (forward-compatible to the'
      echo "# GB10's sm_121); FlashInfer JITs the FP4/MoE paths for the device at runtime."
    else
      # Locally-built image (e.g. a patched vLLM) referenced by tag — NOT portable until built.
      echo "# NOTE: this config uses a LOCALLY-BUILT vLLM ${ver} image (\`${VLLM_IMAGE}\`), not a portable"
      echo '# upstream digest — it must be built on the host before this launcher will run. See its'
      echo '# Dockerfile under backends/vllm/images/ and the matching entry in backends/vllm/image.lock.'
      echo "# Blackwell kernels are sm_120 (forward-compatible to the GB10's sm_121); FlashInfer JITs FP4/MoE."
    fi
    printf 'export VLLM_IMAGE="%s"  # %s\n' "$VLLM_IMAGE" "$ver"
    printf 'export MODEL="%s"\n' "$MODEL"
    [ -n "$MODEL_REVISION" ] && printf 'export MODEL_REVISION="%s"   # pinned for reproducibility\n' "$MODEL_REVISION"
    if [ -n "$MAX_MODEL_LEN" ]; then
      echo
      echo '# Validated serving context (the benchmark shape). Lower it to raise the guaranteed concurrency'
      echo "# floor; raise toward the model's native context for long-context serving (KV pool = util below)."
      printf 'export MAX_MODEL_LEN=%s\n' "$MAX_MODEL_LEN"
    fi
    echo
    printf 'NAME="${NAME:-%s}"\n' "$nodef"
    echo 'PORT="${PORT:-8000}"'
    echo 'HF_CACHE="${HF_HOME:-$HOME/.cache/huggingface}"'
    echo
    echo '# Replace any prior container of this name.'
    echo 'docker rm -f "${NAME}" 2>/dev/null || true'
    echo
    echo 'docker run -d --name "${NAME}" \'
    printf '\t--gpus all \\\n'
    printf '\t--ipc=host \\\n'
    printf '\t-p "${PORT}:8000" \\\n'
    printf '\t-v "${HF_CACHE}:/root/.cache/huggingface" \\\n'
    printf '\t-e TOKENIZERS_PARALLELISM=false \\\n'
    printf '\t-e "HF_TOKEN=${HF_TOKEN:-}" \\\n'
    local kv; for kv in "${VLLM_ENV[@]}"; do printf '\t-e %s \\\n' "$(shq "$kv")"; done
    printf '\t"${VLLM_IMAGE}" \\\n'
    local i n=${#serve_args[@]}
    for i in "${!serve_args[@]}"; do
      if [ "$i" -lt "$((n - 1))" ]; then
        printf '\t\t%s \\\n' "${serve_args[i]}"
      else
        printf '\t\t%s\n' "${serve_args[i]}"
      fi
    done
  } > "$out"
  chmod +x "$out"
  echo "${out#"$REPO_ROOT"/}"
}

[ "$#" -ge 1 ] || { echo "usage: gen_launcher.sh <final_runbook.sh> ..." >&2; exit 2; }
for rb in "$@"; do gen_one "$rb"; done
