#!/usr/bin/env bash
# gen_launcher.sh <final_runbook.sh> [<final_runbook.sh> ...] — emit a self-contained, executable
# docker launch script under launchers/ for each promoted `_final.sh`. The launcher inlines the
# pinned image digest + model + revision + validated serving flags (no dependency on the repo,
# adapter.sh, or image.lock) so it can be copied to any GB10-class host and run to serve the model.
# Mirrors backends/vllm/adapter.sh cmd_up() exactly, but runs FOREGROUND (--rm; Ctrl-C stops+cleans).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck disable=SC1091
source "$REPO_ROOT/backends/vllm/image.lock"
OUTDIR="$REPO_ROOT/launchers"; mkdir -p "$OUTDIR"

gen_one() {
  local rb="$1"
  [ -f "$rb" ] || { echo "not found: $rb" >&2; return 1; }
  # Source the runbook in a clean set of vars (subshell-free: reset each time).
  local MODEL="" SERVED_NAME="" MODEL_REVISION="" VLLM_IMAGE="$AHL_VLLM_DEFAULT_IMAGE"
  local VLLM_ENTRYPOINT_SERVE="$AHL_VLLM_DEFAULT_ENTRYPOINT_SERVE"
  local VLLM_FLAGS=() VLLM_ENV=()
  # shellcheck disable=SC1090
  source "$rb"
  : "${MODEL:?$rb must set MODEL}"; : "${SERVED_NAME:=$MODEL}"

  local base; base="$(basename "$rb" .sh)"; base="${base%_final}"
  local out="$OUTDIR/${base}.sh"

  {
    echo '#!/usr/bin/env bash'
    echo "# AUTO-GENERATED by scripts/gen_launcher.sh from runbooks/.../$(basename "$rb")."
    echo "# Canonical, fully-validated vLLM serve config (passed all three gates). Self-contained:"
    echo "# pinned image digest + model + revision + flags inlined. Serves on http://HOST:PORT/v1."
    echo "#   ./$(basename "$out")            # serve in the foreground (Ctrl-C stops + removes the container)"
    echo "#   PORT=8001 NAME=foo ./$(basename "$out")   # override the port / container name"
    echo '#   (needs: docker + NVIDIA runtime; the model weights pulled to the HF cache, or HF_TOKEN set to fetch.)'
    echo 'set -euo pipefail'
    echo
    printf 'VLLM_IMAGE=%q\n' "$VLLM_IMAGE"
    printf 'MODEL=%q\n' "$MODEL"
    printf 'MODEL_REVISION=%q\n' "$MODEL_REVISION"
    printf 'SERVED_NAME=%q\n' "$SERVED_NAME"
    echo 'PORT="${PORT:-8000}"'
    printf 'NAME="${NAME:-vllm-%s}"\n' "$SERVED_NAME"
    echo 'HF_CACHE="${HF_HOME:-$HOME/.cache/huggingface}"'
    echo
    echo '# env passed into the container (HF_TOKEN for gated/uncached pulls, plus any runbook VLLM_ENV)'
    echo 'ENV_ARGS=( -e "HF_TOKEN=${HF_TOKEN:-}" )'
    local kv; for kv in "${VLLM_ENV[@]}"; do printf 'ENV_ARGS+=( -e %q )\n' "$kv"; done
    echo
    echo '# validated serving flags (one token per line; exact, including JSON values)'
    echo 'VLLM_FLAGS=('
    local f; for f in "${VLLM_FLAGS[@]}"; do printf '  %q\n' "$f"; done
    echo ')'
    echo
    echo 'REV_ARGS=(); [ -n "$MODEL_REVISION" ] && REV_ARGS=( --revision "$MODEL_REVISION" )'
    echo 'docker rm -f "$NAME" >/dev/null 2>&1 || true'
    echo 'echo "serving $SERVED_NAME ($MODEL${MODEL_REVISION:+ @$MODEL_REVISION}) on http://0.0.0.0:${PORT}/v1 — Ctrl-C to stop" >&2'
    echo
    echo 'exec docker run --rm --name "$NAME" --ipc=host --gpus all \'
    echo '  -p "${PORT}:8000" "${ENV_ARGS[@]}" \'
    echo '  -v "${HF_CACHE}:/root/.cache/huggingface" \'
    if [ "$VLLM_ENTRYPOINT_SERVE" = "true" ]; then
      echo '  "$VLLM_IMAGE" "$MODEL" \'   # image ENTRYPOINT is already `vllm serve`
    else
      echo '  "$VLLM_IMAGE" vllm serve "$MODEL" \'
    fi
    echo '    --served-model-name "$SERVED_NAME" "${REV_ARGS[@]}" "${VLLM_FLAGS[@]}"'
  } > "$out"
  chmod +x "$out"
  echo "${out#"$REPO_ROOT"/}"
}

[ "$#" -ge 1 ] || { echo "usage: gen_launcher.sh <final_runbook.sh> ..." >&2; exit 2; }
for rb in "$@"; do gen_one "$rb"; done
